remote_theme: mmistakes/minimal-mistakes
# theme: jekyll-theme-minimal
title: L'Chayim Study Caffe
description: This is the new branch of L'Chayim study cafe in Gojan, Ansan city. 
footer:
  links:
   - label: "GitHub"
     icon: "fab fa-fw fa-github"
     url: "https://lchayim.github.io/gojan-labs"

author:
  name: "L'Chayim Ansan Gojan"
  bio: >-
   My name is Lchayim

main:
  - title: "About me"
    url: /about/
  - title: "Posts"
    url: /years/
  - title: "Pages"
    url: /pages/
  - title: "Tags"
    url: /tags/
